# Site settings
title: J-Slow
baseurl: ''

# Build settings
markdown: kramdown

translations:
  en:
    biography:
      nav: Biography
      text: |
        J-Slow is an artist who was born in Paris in 1989.
        He started to write his first songs at sixteen years old. His youth was influenced by the afro american music (Rap, Rnb, Soul & Pop).

        After he met two of his close friends, Srabimachine (beatmaker) and Joy Thomass (Singer) J-Slow dropped his first mixtape in 2011 named "Le Jour J" this tape was more like a training tape but it was with his 2nd mixtape "Tapis Rouge" that the media started to get interest on his work. He had a distribution deal with the label Believe for his 1st ep "New Wave"  in 2014 and he's about to release his second ep soon.

  fr:
    biography:
      nav: Biographie
      text: |
        J-Slow, de son vrai nom Kévin Madou né le 05 avril 1989, commence à écrire ses premiers textes à l’âge de 16 ans. Inspiré par l’énergie émanant du rap américain pendant son enfance avec des artistes telles que (Notorious BIG, Jay-Z, Snoop Dogg ou encore 2 Pac) et plus particulièrement dans les années 2000 avec (Lil Wayne, Dipset, Max B, Wiz Khalifa, Kanye West) et beaucoup d’autres qui se pris de passion pour la musique urbaine. Il tomba également accro au rap français grâce à des noms telles que (Doc Gyneco, Arsenïk, Lunatic, Secteur Ä ou encore IAM)
        C’est quelques années plus tard, en 2010 suite à la rencontre de différents artistes rappeurs, qu’il élabore son premier projet musical avec l’aide de deux amis , SrabiMachine (Beatmaker) & Joy Thomass (Chanteur). “Le Jour J” (Mixtape ) sort le 23 Décembre 2011 et aura un effet propulseur sur le travail musical du jeune rappeur.
        Près d’un an après, suite à la sortie de sa seconde mixtape, “Tapis Rouge”, J-Slow fait parler de lui grâce à son univers musical et ses visuels toujours bien realisés.
        Bien reçu par les médias underground ou plus connus, J-Slow se verra recompensé par plusieurs articles très positifs sur son travail.
        Il nous délivre son premier ep “New Wave” le 10 mars 2014 distribué par le label Believe sur toutes les plateformes de téléchargement légale.
        Après un an passé à Londres au côté de son ami de toujours SrabiMachine installé labas depuis plusieurs années que le Jeune Slow nous revient avec un nouvel ep “Cash Mire” entièrement produit par son acolyte. La sortie du projet est prevue le 10 Mai prochain.


collections:
  photos:

photos:
  - path: 'photos/photo1.jpg'
  - path: 'photos/photo2.jpg'
  - path: 'photos/photo3.jpg'
  - path: 'photos/photo4.jpg'