# Site settings
title: J-Slow
baseurl: ''

# Build settings
markdown: kramdown

translations:
  en:
    biography:
      nav: Biography
      text: |
        J-Slow is an artist who was born in Paris in 1989.
        He started to write his first songs at sixteen years old. His youth was influenced by the afro american music (Rap, Rnb, Soul & Pop).

        After he met two of his close friends, Srabimachine (beatmaker) and Joy Thomass (Singer) J-Slow dropped his first mixtape in 2011 named "Le Jour J" this tape was more like a training tape but it was with his 2nd mixtape "Tapis Rouge" that the media started to get interest on his work. He had a distribution deal with the label Believe for his 1st ep "New Wave"  in 2014 and he's about to release his second ep soon.

  fr:
    biography:
      nav: Biographie
      text: |
       Jeune Slow, né en 1989 à Paris, commence à écrire ses premiers textes à l’âge de 16 ans. Inspiré par la musique Afro-Americaine; R’n’B, Soul, Pop et plus particulièrement par l’énergie émanant du Rap américain des années 90; Notorious BIG, 2PAC, Jay-Z, Snoop Dogg… & des années 2000; Kanye West, Lil Wayne, Dipset, Max B, Wiz Khalifa… Jeune Slow se pris de passion pour la musique urbaine. Par la suite, il s’intéresse de près au rap français avec Doc Gynéco, Arsenik, Lunatic & IAM… C’est en 2010, suite à la rencontre de différents artists de rap, qu’il lance son premier projet accompagné du beatmaker Srabimachine & du chanteur Joy Thomass. La mixtape “LE JOUR J” est sortie fin 2011 permettant à Jeune Slow de se propulser musicalement. L’année suivante, Sa deuxième mixtape “TAPIS ROUGE” aura eu un effet révélateur et apportera à J-Slow une audience intéressée par son univers musical. Des plateformes française telles que les Inrockuptibles, Soul-Addict, OFIVE & YARD se sont trouvés séduits par le talent du rappeur. Il enchaîne avec la sortie de son EP “NEW WAVE” en 2014 et revient aujourd’hui avec son dernier projet “CASH MIRE” entièrement produit par le beatmaker Srabimachine.

collections:
  photos:

photos:
  - path: 'photos/photo1.jpg'
  - path: 'photos/photo2.jpg'
  - path: 'photos/photo3.jpg'
  - path: 'photos/photo4.jpg'